# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-08 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200924_0537'),
        ('coop', '0027_auto_20210731_1603'),
    ]

    operations = [
        # Added this manually It become a nusance so added it in here to shut it up
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        # end nusance
        migrations.CreateModel(
            name='Agent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('userprofile.profile',),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='month_joined',
            field=models.PositiveIntegerField(blank=True, choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')], null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='year_joined',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
