# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-13 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0029_auto_20211013_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='external_data_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='external_data_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
