# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-12-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0030_auto_20211013_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='trust_network_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='borrower_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
