# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-04-22 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0031_auto_20211216_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='ensuubuko_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='ensuubuko_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
