# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-04 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0033_cooperativemember_ensuubuko_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='ensuubuko_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cooperativemember',
            name='ensuubuko_savings_product',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
