# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0034_auto_20220504_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativemember',
            name='ensuubuko_savings_id',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='ensuubuko_savings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cooperativemember',
            name='ensuubuko_savings_product',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
