# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-05-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0035_auto_20220504_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='ensuubuko_savings_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
