# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0036_auto_20220504_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='mobis_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='mobis_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='mobis_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
