# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-08 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0037_auto_20221108_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='saving_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
