# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-03 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0039_auto_20230615_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativemember',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.Cooperative'),
        ),
    ]
