# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0040_auto_20230703_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKOMemberPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyId', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Farm Name')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('cooperative_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coop.CooperativeMember')),
            ],
            options={
                'db_table': 'oko_policy',
            },
        ),
    ]
