# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-07-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0041_okomemberpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='okomemberpolicy',
            name='claim_status',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='okomemberpolicy',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
