# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_auto_20211009_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcontent',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
