# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-12 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20211012_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcontent',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
    ]
