# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-10-13 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_trainingcontent_thematic_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='trainingcontent',
            unique_together=set([('thematic_area', 'sequence')]),
        ),
    ]
